### ISSUE TITLE
Is this free to use or commercial?

### ISSUE THREAD

**Issue by muhdkhokhar** [exceljava/jinx-com4j#5]

**Comment by tonyroberts** [comment]
See the README and LICENSE files.

**Comment by muhdkhokhar** [comment]
ok thanks but don't think so its very clear but thanks anyway.

**Comment by tonyroberts** [comment]
Sorry if it's not clear. As per the LICENSE file,

Permission is hereby granted, **free of charge**, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction,

For Jinx and com4j, see their respective license terms. Neither are included in this repo, but you will need both if you want to use this repo for anything. Jinx is commercial software (see https://exceljava.com, as per the readme), com4j is licensed under it's own license which you will have to read (free to use with some limitations).
